### ISSUE TITLE
this library can't install on linux

### ISSUE THREAD

**Issue by myaxxxxx** [microsoft/DWriteShapePy#2]
Hi
    Firstly, Thank you very much for implementing DwriteShapePy in python, and I have run it on windows. But I can't pip it on various Linux platforms. So I want to ask whether DWriteShapePy only installs in windows. Thanks.

**Comment by paullinnerud** [comment]
DWriteShapePy is a Python extension that exposes parts of Microsoft Direct Write to the Python environment. DWriteShapePy calls the Direct Write that exists on the system so it currently only works on Windows.

**Comment by myaxxxxx** [comment]
OK, thanks
